# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ce12462b7e3cdc82016af4326a6095a12b11841051d720a2b2b436df98531c1c315d160b315f00877b23a0cac958624bba75feff9978905df24dc79e6b4a135

test:
  secret_key_base: 2f1b4f7345a1a8638e0f4369b4339c23a7f1ae17fa465720268680dd03b578e8fe21c279ccb2d909e6211368a7cb68e2db24e1c82dfb466c503caf69ba84129e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
